config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rooms do
    resources :messages
    collection do
      post :search
    end
  end
  # leave_room_path(room)
  get 'rooms/leave/:id', to: 'rooms#leave', as: 'leave_room'
  # join_room_path(room)
  get 'rooms/join/:id', to: 'rooms#join', as: 'join_room'

  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<section class="bg-gray-900 text-white">
  <div
    class="mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center"
  >
    <div class="mx-auto max-w-3xl text-center">
      <h1
        class="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-5xl"
      >
        Understand Relations

        <span class="sm:block"> Increase Conversion. </span>
      </h1>

      <% if current_user %>
        <%=link_to"Start Chat",rooms_path,class:"my-3 block w-full rounded border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-white focus:outline-none focus:ring active:text-opacity-75 sm:w-auto"%>
      <%else%>
      <p class="mx-auto mt-4 max-w-xl sm:text-xl sm:leading-relaxed">
        What makes our product work is the way we're tightly focused on messaging and being as SMS replacement.
      </p>

      <div class="mt-8 flex flex-wrap justify-center gap-4">
      <%=link_to"Get Started",new_user_registration_path,class:"block w-full rounded border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-white focus:outline-none focus:ring active:text-opacity-75 sm:w-auto"%>
      <%=link_to "Login",new_user_session_path,class:"block w-full rounded border border-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-blue-600 focus:outline-none focus:ring active:bg-blue-500 sm:w-auto" %>
      <% end %>
      </div>
    </div>
  </div>
</section>