config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rooms do
    resources :messages
    collection do
      post :search
    end
  end
  # leave_room_path(room)
  get 'rooms/leave/:id', to: 'rooms#leave', as: 'leave_room'
  # join_room_path(room)
  get 'rooms/join/:id', to: 'rooms#join', as: 'join_room'

  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_update_commit { broadcast_if_public }
  has_many :messages
  has_many :participants, dependent: :destroy
  has_many :joinables, dependent: :destroy
  has_many :joined_users, through: :joinables, source: :user

  def broadcast_if_public
    broadcast_latest_message
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

  def participant?(room, user)
    room.participants.where(user:).exists?
  end

  def latest_message
    messages.includes(:user).order(created_at: :desc).first
  end

  def broadcast_latest_message
    last_message = latest_message

    return unless last_message

    room_target = "room_#{id} last_message"
    user_target = "room_#{id} user_last_message"
    sender = Current.user.eql?(last_message.user) ? Current.user : last_message.user

    broadcast_update_to('rooms',
                        target: room_target,
                        partial: 'rooms/last_message',
                        locals: {
                          room: self,
                          user: last_message.user,
                          last_message:
                        })
    broadcast_update_to('rooms',
                        target: user_target,
                        partial: 'users/last_message',
                        locals: {
                          room: self,
                          user: last_message.user,
                          last_message:,
                          sender:
                        })
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  include RoomsHelper
  before_action :authenticate_user!
  before_action :set_status
  def index
    @room = Room.new
    @joined_rooms = current_user.joined_rooms.order('last_message_at DESC')
    @rooms = search_rooms
    current_user.update(current_room: nil)

    @users = User.all_except(current_user)
    render 'index'
  end

  def show
    @single_room = Room.find(params[:id])
    current_user.update(current_room: @single_room)

    @room = Room.new
    @rooms = search_rooms
    @joined_rooms = current_user.joined_rooms.order('last_message_at DESC')

    @message = Message.new

    pagy_messages = @single_room.messages.includes(:user).order(created_at: :desc)
    @pagy, messages = pagy(pagy_messages, items: 10)
    @messages = messages.reverse

    @users = User.all_except(current_user)
    render 'index'
  end

  def create
    @room = Room.create(name: params['room']['name'])
    redirect_to @room
  end

  def search
    @rooms = search_rooms
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('search_results',
                              partial: 'rooms/search_results',
                              locals: { rooms: @rooms })
        ]
      end
    end
  end

  def join
    @room = Room.find(params[:id])
    current_user.joined_rooms << @room
    redirect_to @room
  end

  def leave
    @room = Room.find(params[:id])
    current_user.joined_rooms.delete(@room)
    redirect_to rooms_path
  end

  private

  def set_status
    current_user&.update!(status: User.statuses[:online])
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
  def search_rooms
    if params[:name_search].present? && params[:name_search].length.positive?
      Room.public_rooms
          .where
          .not(id: current_user.joined_rooms.pluck(:id))
          .where('name ILIKE ?', "%#{params[:name_search]}%")
          .order(name: :asc)
    else
      []
    end
  end

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end
end

app/views/rooms/_joinable_link.html.erb
<% if current_user.joined_room?(room) %>
  <%= link_to leave_room_path(room), method: :delete, data: {turbo: "false"} do %>
    <i class="bi bi-dash-square room-leave-link-icon"></i>
  <% end %>
<% else %>
  <%= link_to join_room_path(room), method: :delete, data: {turbo: "false"} do %>
    <i class="bi bi-plus-square room-join-link-icon"></i>
  <% end %>
<% end %>

app/views/rooms/_last_message.html.erb
<% unless last_message.nil? %>
  <div class="row">
    <div class="col-12 d-flex align-items-center justify-content-between">
      <em class="last-message"><%= "#{last_message.user.email} sent a message".truncate(40) %></em>
      <%= content_tag(:em, class:"last-message-time", 
        data: {
          time: last_message.created_at.to_i
          }) do %>
        <%= "#{time_ago_in_words(last_message.created_at)} ago"%>
      <% end %>
    </div>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<% if room.id.eql?(current_user.current_room) %>
  <% isActive = 'active' %>
<% else %>
  <% isActive = '' %>
<% end %>
<div class="room">
  <li class="list-group-item room_list_item <% isActive %>">
    <div class="row">
      <div class="col-12 d-flex align-items-center justify-content-between">
        <%= turbo_frame_tag dom_id(room) do %>
          <%= link_to room.name, room_path(room, name_search: params[:name_search]), data: {turbo: "false"}, class: "ms-2 me-auto" %>
        <% end %>
        <%= render 'rooms/joinable_link', room: room %>
      </div>
    </div>
    <%= turbo_frame_tag [dom_id(room), "last_message"] do %>
      <%= render "rooms/last_message", 
        room: room, 
        user: user, 
        last_message: last_message %>
    <% end %>
  </li>
</div>

app/views/rooms/_room_container.html.erb
<li class="list-group-item room_list_item">
  <div class="row">
    <div class="col-12 d-flex align-items-center justify-content-between">
      <%= link_to room.name, room_path(room, name_search: params[:name_search]), data: {turbo: "false"}, class: "ms-2 me-auto" %>
      <%= render 'rooms/joinable_link', room: room %>
    </div>
  </div>
  <%= turbo_frame_tag [dom_id(room), "last_message"] do %>
    <%= render "rooms/last_message", 
        room: room, 
        user: user, 
        last_message: last_message %>
  <% end %>
</li>

app/views/rooms/_rooms.html.erb
<% rooms.each do |room| %>
  <%= render 'rooms/room',
        room: room,
        last_message: room.latest_message, 
        user: user %>
<% end %>

app/views/rooms/_search_form.html.erb
<%= form_with url: search_rooms_path, 
    method: :post, 
    id: "room_search_form",
    data: {controller: "debounce"} do |form| %>
  <%= form.search_field :name_search, 
    value: params[:name_search],
    class: 'room_search_field', 
    placeholder: "Search Rooms to Join...",
    data: { action: "input->debounce#search"} %>
<% end %>
<div id="search_results">
  <%= render 'rooms/search_results', rooms: @rooms %>
</div>

app/views/rooms/_search_results.html.erb
<% rooms.each do |room| %>
  <li class="list-group-item d-flex align-items-center justify-content-between room_list_item">
    <%= link_to room.name, room_path(id: room.id, name_search: params[:name_search]), data: {turbo: "false"}%>
    <%= render 'rooms/joinable_link', room: room %>
  </li>
<% end %>

app/views/rooms/index.html+turbo_frame.erb
<%= turbo_frame_tag "page_handler" do %>
  <%= turbo_stream_action_tag(
    "prepend",
    target: "messages-container",
    template: %(#{render @messages})
    ) %>
  <%= turbo_stream_action_tag(
    "replace",
    target: "pager",
    template: %(#{render "messages/pager", pagy: @pagy})
    ) %>
<% end %>

app/views/rooms/index.html.erb
<%= turbo_frame_tag "appearance_channel" %>
<div id="appearance_channel"></div>
<div id="chatroom_container" class="row bg-dark text-light">
  <div id="side_panel" class="col-md-4 col-sm-4">
    <li class="list-group-item d-flex align-items-center justify-content-between user_list_item">
      <div class="icon-container">
        <%= link_to image_tag(current_user.chat_avatar, class: 'chat_pfp'), current_user %>
        <%= turbo_stream_from "user_status" %>
        <div>
          <%= render "users/status", user: current_user %>
        </div>
      </div>
      <div class='ms-2 me-auto username'>
        <%= current_user.email%>
      </div>
    </li>
    <h4> Users </h4>
    <%= turbo_stream_from "users" %>
    <div id="users" data-controller="user-list">
      <%= render "users/users", users: @users %>
    </div>
    <h4> Rooms </h4>
    <%= turbo_stream_from "rooms" %>
    <%= render 'layouts/new_room_form' %>
    <%= render 'rooms/search_form' %>
    <div id="rooms" data-controller="room-list">
      <%= render "rooms/rooms", rooms: @joined_rooms, user: current_user %>
    </div>
  </div>
  <div id="room_container"
  class="col-md-8 col-sm-8 bg-dark text-light">
    <% if @single_room %>
      <div id="single_room">
        <h4 class="text-center"> <%= @user&.email || @single_room.name %> </h4>
        <%= turbo_stream_from @single_room %>
        <div id="messages" data-controller="scroll">
          <%= turbo_frame_tag "page_handler" %>
          <%= render "messages/pager", pagy: @pagy %>
          <div id="messages-container">
            <%= render @messages %>
          </div>
        </div>
        <%= render 'layouts/new_message_form' %>
      </div>
    <% end %>
  </div>
</div>